# Generated by Django 3.2.8 on 2021-11-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResetPassword',
        ),
    ]
